---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: "instance-${image:-rockylinux8}${TOX_ENVNAME}"
    image: "geerlingguy/docker-${image:-rockylinux8}-ansible:${tag:-latest}"
    pre_build_image: true
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp
    privileged: true
    cgroupns_mode: host

provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  env:
    ANSIBLE_ROLES_PATH: "../../roles"

lint: |
  yamllint roles/ntp
  ansible-lint roles/ntp

verifier:
  name: ansible
