---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: "instance-${image:-centos}-${tag:-stream8}_${TOX_ENVNAME}"
    image: "${namespace:-quay.io}/${image:-centos/centos}:${tag:-stream8}"
    pre_build_image: true
    privileged: true
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    command: "/usr/sbin/init"
    environment: { container: docker }

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../roles"

lint: |
  yamllint roles/ntp
  ansible-lint roles/ntp

verifier:
  name: ansible
