---
dependency:
  name: galaxy
driver:
  name: docker

platforms:
  - name: "instance-${osname:-centos}-${tag:-stream8}_${TOX_ENVNAME}"
    image: "${image:-quay.io/centos/centos}:${tag:-stream8}"
    pre_build_image: true

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../roles"

lint: |
  yamllint roles/users
  ansible-lint roles/users

verifier:
  name: ansible
...
