---
dependency:
  name: galaxy
driver:
  name: docker

platforms:
  - name: "instance-${image:-centos}-${tag:-stream8}_${TOX_ENVNAME}"
    image: "${namespace:-quay.io}/${image:-centos/centos}:${tag:-stream8}"
    pre_build_image: true

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../roles"

lint: |
  yamllint roles/ansible-role-users
  ansible-lint roles/ansible-role-users

verifier:
  name: ansible
...
